apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: volca-frontend
  name: volca-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volca-frontend
  template:
    metadata:
      labels:
        app: volca-frontend
    spec:
      containers:
      - image: registry.hub.docker.com/tuanpa1993/volca-frontend:$VOLCA_FRONTEND_TAG
        imagePullPolicy: Always
        name: volca-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: volca-frontend-service
  namespace: default
  labels:
    app: volca-frontend
spec:
  type: LoadBalancer
  selector:
    app: volca-frontend
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
