apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: volca-frontend
  name: volca-frontend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volca-frontend
  template:
    metadata:
      labels:
        app: volca-frontend
    spec:
      containers:
      - image: registry.hub.docker.com/tuanpa1993/volca-frontend:$VOLCA_FRONTEND_TAG
        imagePullPolicy: Always
        name: volca-frontend
# - apiVersion: apps/v1
#   kind: Deployment
#   metadata:
#     labels:
#       app: volca-frontend
#     name: volca-frontend
#     namespace: default
#   spec:
#     replicas: 1
#     selector:
#       matchLabels:
#         app: volca-frontend
#     template:
#       metadata:
#         labels:
#           app: volca-frontend
#       spec:
#         containers:
#         - image: registry.hub.docker.com/tuanpa1993/volca-frontend:$VOLCA_FRONTEND_TAG
#           imagePullPolicy: Always
#           name: volca-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: volca-frontend-service
  namespace: default
  labels:
    app: volca-frontend
spec:
  type: LoadBalancer
  selector:
    app: volca-frontend
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
# - apiVersion: v1
#   kind: Service
#   metadata:
#     creationTimestamp: "2019-10-13T05:55:49Z"
#     labels:
#       app: volca-api
#     name: volca-api-service
#     namespace: default
#     resourceVersion: "269934"
#     selfLink: /api/v1/namespaces/default/services/volca-api-service
#     uid: 1bd20f9a-ed7e-11e9-a8f5-42010a800194
#   spec:
#     clusterIP: 10.0.1.123
#     externalTrafficPolicy: Cluster
#     ports:
#     - nodePort: 32165
#       port: 80
#       protocol: TCP
#       targetPort: 80
#     selector:
#       app: volca-api
#     sessionAffinity: None
#     type: LoadBalancer
#   status:
#     loadBalancer:
#       ingress:
#       - ip: 35.232.217.182
# - apiVersion: v1
#   kind: Service
#   metadata:
#     creationTimestamp: "2019-10-13T10:42:41Z"
#     labels:
#       app: volca-frontend
#     name: volca-frontend-service
#     namespace: default
#     resourceVersion: "334694"
#     selfLink: /api/v1/namespaces/default/services/volca-frontend-service
#     uid: 2ecd1b76-eda6-11e9-941f-42010a800074
#   spec:
#     clusterIP: 10.0.7.110
#     externalTrafficPolicy: Cluster
#     ports:
#     - nodePort: 30061
#       port: 80
#       protocol: TCP
#       targetPort: 80
#     selector:
#       app: volca-frontend
#     sessionAffinity: None
#     type: LoadBalancer
# - apiVersion: apps/v1
#   kind: ReplicaSet
#   metadata:
#     annotations:
#       deployment.kubernetes.io/desired-replicas: "3"
#       deployment.kubernetes.io/max-replicas: "4"
#       deployment.kubernetes.io/revision: "5"
#       deployment.kubernetes.io/revision-history: 1,3
#     creationTimestamp: "2019-10-13T05:42:14Z"
#     generation: 14
#     labels:
#       app: volca-api
#       pod-template-hash: 74b89dd9fb
#     name: volca-api-74b89dd9fb
#     namespace: default
#     ownerReferences:
#     - apiVersion: apps/v1
#       blockOwnerDeletion: true
#       controller: true
#       kind: Deployment
#       name: volca-api
#       uid: 35adaefb-ed7c-11e9-a8f5-42010a800194
#     resourceVersion: "342134"
#     selfLink: /apis/apps/v1/namespaces/default/replicasets/volca-api-74b89dd9fb
#     uid: 35aeb6e4-ed7c-11e9-a8f5-42010a800194
#   spec:
#     replicas: 0
#     selector:
#       matchLabels:
#         app: volca-api
#         pod-template-hash: 74b89dd9fb
#     template:
#       metadata:
#         creationTimestamp: null
#         labels:
#           app: volca-api
#           pod-template-hash: 74b89dd9fb
#       spec:
#         containers:
#         - image: registry.hub.docker.com/tuanpa1993/volca-api
#           imagePullPolicy: Always
#           name: volca-api
#           resources: {}
#           terminationMessagePath: /dev/termination-log
#           terminationMessagePolicy: File
#         dnsPolicy: ClusterFirst
#         restartPolicy: Always
#         schedulerName: default-scheduler
#         securityContext: {}
#         terminationGracePeriodSeconds: 30
#   status:
#     observedGeneration: 14
#     replicas: 0
# - apiVersion: apps/v1
#   kind: ReplicaSet
#   metadata:
#     annotations:
#       deployment.kubernetes.io/desired-replicas: "1"
#       deployment.kubernetes.io/max-replicas: "2"
#       deployment.kubernetes.io/revision: "6"
#       deployment.kubernetes.io/revision-history: 2,4
#     creationTimestamp: "2019-10-13T06:23:41Z"
#     generation: 15
#     labels:
#       app: volca-api
#       pod-template-hash: 8d66df8d7
#     name: volca-api-8d66df8d7
#     namespace: default
#     ownerReferences:
#     - apiVersion: apps/v1
#       blockOwnerDeletion: true
#       controller: true
#       kind: Deployment
#       name: volca-api
#       uid: 35adaefb-ed7c-11e9-a8f5-42010a800194
#     resourceVersion: "619706"
#     selfLink: /apis/apps/v1/namespaces/default/replicasets/volca-api-8d66df8d7
#     uid: 002b3141-ed82-11e9-a8f5-42010a800194
#   spec:
#     replicas: 1
#     selector:
#       matchLabels:
#         app: volca-api
#         pod-template-hash: 8d66df8d7
#     template:
#       metadata:
#         creationTimestamp: null
#         labels:
#           app: volca-api
#           pod-template-hash: 8d66df8d7
#       spec:
#         containers:
#         - image: registry.hub.docker.com/tuanpa1993/volca-api:latest
#           imagePullPolicy: Always
#           name: volca-api
#           resources: {}
#           terminationMessagePath: /dev/termination-log
#           terminationMessagePolicy: File
#         dnsPolicy: ClusterFirst
#         restartPolicy: Always
#         schedulerName: default-scheduler
#         securityContext: {}
#         terminationGracePeriodSeconds: 30
#   status:
#     availableReplicas: 1
#     fullyLabeledReplicas: 1
#     observedGeneration: 15
#     readyReplicas: 1
#     replicas: 1
# - apiVersion: apps/v1
#   kind: ReplicaSet
#   metadata:
#     annotations:
#       deployment.kubernetes.io/desired-replicas: "1"
#       deployment.kubernetes.io/max-replicas: "2"
#       deployment.kubernetes.io/revision: "1"
#     creationTimestamp: "2019-10-13T10:41:43Z"
#     generation: 2
#     labels:
#       app: volca-frontend
#       pod-template-hash: 84bd9fd5b6
#     name: volca-frontend-84bd9fd5b6
#     namespace: default
#     ownerReferences:
#     - apiVersion: apps/v1
#       blockOwnerDeletion: true
#       controller: true
#       kind: Deployment
#       name: volca-frontend
#       uid: 0bed51c4-eda6-11e9-941f-42010a800074
#     resourceVersion: "619673"
#     selfLink: /apis/apps/v1/namespaces/default/replicasets/volca-frontend-84bd9fd5b6
#     uid: 0bee33ce-eda6-11e9-941f-42010a800074
#   spec:
#     replicas: 1
#     selector:
#       matchLabels:
#         app: volca-frontend
#         pod-template-hash: 84bd9fd5b6
#     template:
#       metadata:
#         creationTimestamp: null
#         labels:
#           app: volca-frontend
#           pod-template-hash: 84bd9fd5b6
#       spec:
#         containers:
#         - image: registry.hub.docker.com/tuanpa1993/volca-frontend
#           imagePullPolicy: Always
#           name: volca-frontend
#           resources: {}
#           terminationMessagePath: /dev/termination-log
#           terminationMessagePolicy: File
#         dnsPolicy: ClusterFirst
#         restartPolicy: Always
#         schedulerName: default-scheduler
#         securityContext: {}
#         terminationGracePeriodSeconds: 30
#   status:
#     availableReplicas: 1
#     fullyLabeledReplicas: 1
#     observedGeneration: 2
#     readyReplicas: 1
#     replicas: 1
# - apiVersion: autoscaling/v1
#   kind: HorizontalPodAutoscaler
#   metadata:
#     annotations:
#       autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2019-10-13T05:42:29Z","reason":"ReadyForNewScale","message":"recommended
#         size matches current size"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2019-10-14T06:37:59Z","reason":"ValidMetricFound","message":"the
#         HPA was able to successfully calculate a replica count from cpu resource utilization
#         (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2019-10-13T08:44:17Z","reason":"DesiredWithinRange","message":"the
#         desired count is within the acceptable range"}]'
#       autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"1m"}}]'
#     creationTimestamp: "2019-10-13T05:42:14Z"
#     labels:
#       app: volca-api
#     name: volca-api-hpa
#     namespace: default
#     resourceVersion: "732276"
#     selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/volca-api-hpa
#     uid: 35bca43c-ed7c-11e9-a8f5-42010a800194
#   spec:
#     maxReplicas: 5
#     minReplicas: 1
#     scaleTargetRef:
#       apiVersion: apps/v1
#       kind: Deployment
#       name: volca-api
#     targetCPUUtilizationPercentage: 80
#   status:
#     currentCPUUtilizationPercentage: 1
#     currentReplicas: 1
#     desiredReplicas: 1
#     lastScaleTime: "2019-10-13T11:19:14Z"
# - apiVersion: autoscaling/v1
#   kind: HorizontalPodAutoscaler
#   metadata:
#     annotations:
#       autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2019-10-13T10:41:58Z","reason":"ScaleDownStabilized","message":"recent
#         recommendations were higher than current one, applying the highest recent
#         recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2019-10-14T06:37:59Z","reason":"ValidMetricFound","message":"the
#         HPA was able to successfully calculate a replica count from cpu resource utilization
#         (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2019-10-14T14:41:57Z","reason":"DesiredWithinRange","message":"the
#         desired count is within the acceptable range"}]'
#       autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"0"}}]'
#     creationTimestamp: "2019-10-13T10:41:43Z"
#     labels:
#       app: volca-frontend
#     name: volca-frontend-hpa
#     namespace: default
#     resourceVersion: "745801"
#     selfLink: /apis/autoscaling/v1/namespaces/default/horizontalpodautoscalers/volca-frontend-hpa
#     uid: 0c0e3965-eda6-11e9-941f-42010a800074
#   spec:
#     maxReplicas: 5
#     minReplicas: 1
#     scaleTargetRef:
#       apiVersion: apps/v1
#       kind: Deployment
#       name: volca-frontend
#     targetCPUUtilizationPercentage: 80
#   status:
#     currentCPUUtilizationPercentage: 0
#     currentReplicas: 1
#     desiredReplicas: 1
#     lastScaleTime: "2019-10-13T10:46:58Z"
# kind: List
# metadata:
#   resourceVersion: ""
#   selfLink: ""
